version: '2'


services:
  tezster15:
    build: .
    image: tezster15
    ports:
      - "0.0.0.0:18731:18731"
    network_mode: host

    command: bash -c "/usr/local/bin/start_nodes.sh && tail -f /dev/null"

     
